[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  base = "frontend/sveltekit/"
  
  # TODO: This is did not work, fix it
  # Don't make Netlify builds if no changes in SvelteKit dir
  # ignore = "git diff HEAD^ HEAD frontend/sveltekit/"
